# Generated by Django 3.0.7 on 2020-06-16 19:32

from django.db import migrations, models
import django.db.models.manager
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa_Juridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão social')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('pagina_comercial_url', models.URLField(blank=True)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='logos', verbose_name='Logo')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Pessoa jurídica',
                'verbose_name_plural': 'Pessoas jurídicas',
                'ordering': ['razao_social'],
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
