# Generated by Django 3.0.7 on 2020-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('texto', models.TextField(max_length=200, verbose_name='Texto')),
                ('icone', models.CharField(choices=[('cog', 'lni-cog'), ('up', 'lni-stats-up'), ('use', 'lni-users'), ('lay', 'lni-layers'), ('mob', 'lni-mobile'), ('roc', 'lni-rocket')], max_length=100, verbose_name='icone')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
