# Generated by Django 3.0.7 on 2020-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-layers', 'Design'), ('lni-users', 'Usuário'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico')], max_length=100, verbose_name='icone'),
        ),
    ]
