# Generated by Django 3.0.7 on 2020-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200714_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='git',
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-stats-up', 'Gráfico'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete'), ('lni-users', 'Usuário'), ('lni-cog', 'Engrenagem'), ('lni-layers', 'Design')], max_length=100, verbose_name='icone'),
        ),
    ]
